# Generated by Django 4.0.2 on 2022-06-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_user_watchlist_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist',
            field=models.ManyToManyField(related_name='cart', to='auctions.Listings'),
        ),
    ]
