# Generated by Django 4.1.1 on 2022-10-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='cart', to='auctions.listings'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
